### ISSUE TITLE
Why the name lo?

### ISSUE THREAD

**Issue by TimiBolu** [just-js/lo#1]
I was wondering why the name.

**Comment by billywhizz** [comment]
for now, am going to create the following repos. this can change later but i think it works well.

**just-js/lo** - this repository - for the low level set of primitives and bindings for system interfaces and common libraries. this will be useful for folks who want to do lower level work directly against system/library api's in JS and/or want to build their own runtimes
**just-js/hi** -  a project build on top of just-js/lo which provides higher level abstractions for writing more standards compliant code cross platform - should implement a significant subsection of the wintercg proposals - to be discussed. not a high priority rn.
**just-js/v8** -  the v8 monolithic library builds for various common platforms
